name: Plan → PR

on:
  issue_comment:
    types: [created]

jobs:
  pr:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null && contains(toJSON(github.event.comment.body), 'APPROVE_PLAN')

    steps:
      - name: Debug Event
        run: |
          echo "Comment body:"
          echo "${{ github.event.comment.body }}"
          echo "Issue number:"
          echo "${{ github.event.issue.number }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push branch
        run: |
          BRANCH="plan-${{ github.event.issue.number }}"
          git fetch origin main
          git checkout -b $BRANCH origin/main
          git push origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: plan-${{ github.event.issue.number }}
          title: "Plan → PR for issue #${{ github.event.issue.number }}"
          body: |
            This PR was automatically created from issue #${{ github.event.issue.number }}
            Triggered by comment: `${{ github.event.comment.body }}`
